export const COMPANY_TYPES = ['Incorporated', 'Pty Ltd'] as const

export const INDUSTRIES = [
  'Accounting',
  'Auditing',
  'Banking',
  'Capital Markets',
  'Investment Management',
  'Venture Capital',
  'Private Equity',
  'Insurance',
  'Reinsurance',
  'Financial Services',
  'FinTech',
  'Payments',
  'Wealth Management',
  'Tax Consulting',
  'Risk Management',
  'Compliance',
  'Legal Services',
  'Law Practice',
  'Alternative Dispute Resolution',
  'Intellectual Property',
  'Corporate Law',
  'International Trade Law',
  'Computer Software',
  'Computer Hardware',
  'Computer Networking',
  'Computer Network Security',
  'Cybersecurity',
  'Cloud Computing',
  'Data Analytics',
  'Big Data',
  'Artificial Intelligence',
  'Machine Learning',
  'Blockchain',
  'Web Development',
  'Mobile Applications',
  'SaaS',
  'IT Services',
  'IT Consulting',
  'Information Services',
  'Database Management',
  'DevOps',
  'QA Testing',
  'Open Source Software',
  'Game Development',
  'Computer Games',
  'Mechanical Engineering',
  'Electrical Engineering',
  'Electronic Manufacturing',
  'Industrial Engineering',
  'Civil Engineering',
  'Structural Engineering',
  'Chemical Engineering',
  'Automotive',
  'Automotive Manufacturing',
  'Aerospace',
  'Aviation Aerospace',
  'Defense & Space',
  'Robotics',
  'Automation',
  'Semiconductor Manufacturing',
  'Embedded Systems',
  'Manufacturing',
  'Industrial Automation',
  'Precision Engineering',
  'Construction',
  'Commercial Real Estate',
  'Residential Real Estate',
  'Property Management',
  'Real Estate Development',
  'Architecture Planning',
  'Interior Design',
  'Urban Planning',
  'Building Materials',
  'Infrastructure Development',
  'Smart Cities',
  'Facilities Management',
  'Surveying',
  'Landscape Architecture',
  'Hospital & Health Care',
  'Medical Practice',
  'Mental Health Care',
  'Pharmaceuticals',
  'Biotechnology',
  'Medical Devices',
  'HealthTech',
  'Telemedicine',
  'Alternative Medicine',
  'Nursing Care',
  'Elder Care',
  'Rehabilitation Services',
  'Veterinary Services',
  'Public Health',
  'Clinical Research',
  'Medical Laboratories',
  'Education Management',
  'E-Learning',
  'Higher Education',
  'Primary Education',
  'Secondary Education',
  'Vocational Training',
  'Corporate Training',
  'Online Education',
  'Educational Technology (EdTech)',
  'Language Learning',
  'Professional Coaching',
  'Career Counseling',
  'Research Institutions',
] as const

export const companyKeys = {
  all: ['companies'] as const,
  companies: () => [...companyKeys.all, 'companies'] as const,
  companiesList: (query: any) =>
    [...companyKeys.companies(), 'list', query] as const,
  companyDetail: (id: string) =>
    [...companyKeys.companies(), 'detail', id] as const,
}
